// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twykjgsexfdiezkcpkfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3eWtqZ3NleGZkaWV6a2Nwa2ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTk3MjAsImV4cCI6MjA1OTg3NTcyMH0.y-LNFdkeEhHLXbfw757L1ndRy1N_EsF7PZFJ7jL7mWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);